import fs from "fs";
import path from "path";

const DATA_PATH = path.join(process.cwd(), "data", "elo.json");
const REQUIRED_KEYS = [
  "meta",
  "corePlayers",
  "players",
  "series",
  "events",
  "sessions",
  "games",
  "headToHead",
];

// Payload is generated by the bgelo repo: `python3 -m bgelo.viz` writes
// output/dashboard_data.json — copy it here as data/elo.json.
export function getEloData() {
  let raw;
  try {
    raw = fs.readFileSync(DATA_PATH, "utf8");
  } catch (err) {
    throw new Error(
      `missing data/elo.json — run \`python3 -m bgelo.viz\` in the bgelo repo ` +
        `and copy output/dashboard_data.json here (${err.message})`,
    );
  }

  const data = JSON.parse(raw);
  const missing = REQUIRED_KEYS.filter((key) => !(key in data));
  if (missing.length > 0) {
    throw new Error(`data/elo.json is missing keys: ${missing.join(", ")}`);
  }
  if (!Array.isArray(data.players) || data.players.length === 0) {
    throw new Error("data/elo.json has no players");
  }
  if (!Array.isArray(data.events) || data.events.length === 0) {
    throw new Error("data/elo.json has no events");
  }
  return data;
}
