import fs from "fs";
import path from "path";

const DATA_PATH = path.join(process.cwd(), "data", "packev.json");
const REQUIRED_KEYS = ["meta", "roles", "cross", "boosters"];

// Payload is generated by the pack-ev repo:
// `uv run pack-ev site-export --site <this repo>` writes data/packev.json.
export function getPackEvData() {
  let raw;
  try {
    raw = fs.readFileSync(DATA_PATH, "utf8");
  } catch (err) {
    throw new Error(
      `missing data/packev.json — run \`uv run pack-ev site-export --site <this repo>\` ` +
        `in the pack-ev repo (${err.message})`,
    );
  }

  const data = JSON.parse(raw);
  const missing = REQUIRED_KEYS.filter((key) => !(key in data));
  if (missing.length > 0) {
    throw new Error(`data/packev.json is missing keys: ${missing.join(", ")}`);
  }
  if (!Array.isArray(data.boosters) || data.boosters.length === 0) {
    throw new Error("data/packev.json has no boosters");
  }
  return data;
}
